class Person(age: Int = 25, name: String) {
    var age: Int = age
        get() = field 
        set(value) {field = value}
        /**
         * getAge & setAge auto generated by the compiler
         * 1st character of a parameter name capitalized + prefix get/set
         **/


    //Explicitly define method returning the age property
    //fun getAge() :Int { return age }
    /** 
     *  Exception in thread "main" java.lang.ClassFormatError: 
     *  Duplicate method name "setAge" with signature "(I)V" 
     *  in class file Person
     **/
     
    //Explicitly define method setting the age property  
    //fun setAge(_age: Int) { age = _age }
    /**
     *  Exception in thread "main" java.lang.ClassFormatError:
     *  Duplicate method name "getAge" with signature "()I"
     *  in class file Person
     **/

     
  /** Here no get/set property and 'accompanying' methods
   *  are declared.
   *  Explicit get/set methods are defined
   *  'name' member is private and accessible through
   *  explicit get/set methods
  private var name: String = name
  fun getName(): String { return name }
  fun setName(_name: String) { name = _name }
     
     
   
         
   
}



fun main() {
    val JonDoe = Person(name = "Mr. Jon Doe")
    JonDoe.age = 30
    println(JonDoe.age)
    println(JonDoe.name)
}
